version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: medicy_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medicy_db
    ports:
      - "3306:3306"
    volumes:
      - medicy_data:/var/lib/mysql
  backend:
    build: ./backend
    container_name: medicy_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/medicy_db
    depends_on:
      - db
volumes:
  medicy_data: